name: azza_musyaffa_kuis
description: Aplikasi kuis sederhana dengan tema biru putih.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.5.5
  just_audio: ^0.10.6
  just_audio_windows: ^0.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/audio/

  fonts:
    - family: Nosifer
      fonts:
        - asset: assets/fonts/Nosifer-Regular.ttf